"""Core memory engine components.

This module contains the foundational components for Memory Layer:
- Data models and enums
- SQLite storage layer
- Vector embeddings
- Hybrid retrieval system
- Memory engine orchestrator
"""

from __future__ import annotations

from memory_layer.core.logging import get_logger, setup_logging
from memory_layer.core.models import (
    ContextResponse,
    ContextResponseModel,
    Memory,
    MemoryCategory,
    MemoryCreate,
    MemoryResponse,
    MemoryScope,
    MemorySource,
    MemoryUpdate,
    Outcome,
    OutcomeRecord,
    SearchQuery,
    SearchResult,
    SearchResultResponse,
    StatsResponse,
    OUTCOME_SCORE_ADJUSTMENTS,
)
from memory_layer.core.storage import (
    ConnectionError,
    MemoryNotFoundError,
    MemoryStorage,
    StorageError,
    StorageStats,
)
from memory_layer.core.embeddings import (
    APIEmbeddingProvider,
    APIError,
    BatchEmbeddingResult,
    Embedding,
    EmbeddingCache,
    EmbeddingConfig,
    EmbeddingError,
    EmbeddingProvider,
    EmbeddingResult,
    LocalEmbeddingProvider,
    MockEmbeddingProvider,
    ModelNotFoundError,
    get_embedding_provider,
)
from memory_layer.core.retrieval import (
    BM25Index,
    CategoryRouter,
    HybridRetriever,
    RetrievalConfig,
)
from memory_layer.core.engine import (
    EngineConfig,
    EngineError,
    EngineNotInitializedError,
    EngineStats,
    LastSearchInfo,
    MemoryEngine,
    create_engine,
)
from memory_layer.core.exceptions import (
    AuthenticationError,
    BeadsNotFoundError,
    CircuitOpenError,
    ConfigurationError,
    DatabaseConnectionError,
    DatabaseIntegrityError,
    DaemonAlreadyRunningError,
    DaemonError,
    ErrorCode,
    ExtractionError,
    HookError,
    HookNotInstalledError,
    InitializationError,
    InvalidResponseError,
    LLMAPIError,
    MCPError,
    MemoryLayerError,
    RateLimitError,
    RetrievalError,
    SDKError,
    SearchTimeoutError,
    ServerError,
    TaskError,
    TaskLinkError,
    TaskSyncError,
    ValidationError,
    format_error,
    is_recoverable,
)
from memory_layer.core.resilience import (
    CircuitBreaker,
    CircuitBreakerConfig,
    CircuitState,
    RetryConfig,
    calculate_backoff,
    get_circuit_breaker,
    reset_all_circuit_breakers,
    retry,
    retry_sync,
    try_multiple,
    with_fallback,
    with_fallback_sync,
    with_timeout,
)

__all__ = [
    # Logging
    "get_logger",
    "setup_logging",
    # Enums
    "MemoryCategory",
    "MemoryScope",
    "MemorySource",
    "Outcome",
    "OUTCOME_SCORE_ADJUSTMENTS",
    # Dataclasses
    "Memory",
    "SearchResult",
    "ContextResponse",
    # Pydantic models
    "MemoryCreate",
    "MemoryUpdate",
    "SearchQuery",
    "OutcomeRecord",
    "MemoryResponse",
    "SearchResultResponse",
    "ContextResponseModel",
    "StatsResponse",
    # Storage
    "MemoryStorage",
    "StorageStats",
    "StorageError",
    "MemoryNotFoundError",
    "ConnectionError",
    # Embeddings
    "EmbeddingProvider",
    "LocalEmbeddingProvider",
    "APIEmbeddingProvider",
    "MockEmbeddingProvider",
    "EmbeddingConfig",
    "EmbeddingResult",
    "BatchEmbeddingResult",
    "EmbeddingCache",
    "Embedding",
    "EmbeddingError",
    "ModelNotFoundError",
    "APIError",
    "get_embedding_provider",
    # Retrieval
    "BM25Index",
    "HybridRetriever",
    "RetrievalConfig",
    "CategoryRouter",
    # Engine
    "MemoryEngine",
    "EngineConfig",
    "EngineStats",
    "EngineError",
    "EngineNotInitializedError",
    "LastSearchInfo",
    "create_engine",
    # Exceptions
    "MemoryLayerError",
    "ErrorCode",
    "DatabaseConnectionError",
    "DatabaseIntegrityError",
    "RetrievalError",
    "SearchTimeoutError",
    "ExtractionError",
    "LLMAPIError",
    "RateLimitError",
    "InvalidResponseError",
    "ServerError",
    "MCPError",
    "HookError",
    "HookNotInstalledError",
    "DaemonError",
    "DaemonAlreadyRunningError",
    "SDKError",
    "AuthenticationError",
    "ValidationError",
    "TaskError",
    "BeadsNotFoundError",
    "TaskSyncError",
    "TaskLinkError",
    "ConfigurationError",
    "InitializationError",
    "CircuitOpenError",
    "format_error",
    "is_recoverable",
    # Resilience
    "RetryConfig",
    "calculate_backoff",
    "retry",
    "retry_sync",
    "CircuitState",
    "CircuitBreakerConfig",
    "CircuitBreaker",
    "get_circuit_breaker",
    "reset_all_circuit_breakers",
    "with_fallback",
    "with_fallback_sync",
    "try_multiple",
    "with_timeout",
]
